stages:
  - test
  - deploy

image: python:3.6

test:
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - pip install coveralls
    - coverage run --source=. -m unittest discover
    - coverage html
    - mv htmlcov/ public/
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - public
    expire_in: 30 days