stages:
  - test
  - push image

test:
  image: python:3.6
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - pip install coveralls
    - coverage run --source=. -m unittest discover
    - coverage html
    - mv htmlcov/ public/
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - public
    expire_in: 30 days

docker build:
  image: docker:latest
  stage: push image
  only:
    - master
  script:
    - docker info
    - docker build -t prozorro/prozorro_tasks .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push prozorro/prozorro_tasks