stages:
  - test
  - push image

test:
  image: python:3.6
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - pip install coveralls
    - coverage run --source=. -m unittest discover
    - coverage html
    - mv htmlcov/ public/
    - coverage report
  tags:
    - kube
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - public
    expire_in: 30 days

docker build:
  image: docker:git
  stage: push image
  only:
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - LATEST_MASTER_COMMIT=$(git log -n 1 origin/master --pretty=format:"%H")
    - if [ "$LATEST_MASTER_COMMIT" = "$CI_COMMIT_SHA" ]; then EXTRA_TAGS="-t $CI_REGISTRY_IMAGE:latest"; fi
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $EXTRA_TAGS .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - if [ "$LATEST_MASTER_COMMIT" = "$CI_COMMIT_SHA" ]; then docker push $CI_REGISTRY_IMAGE:latest; fi
