language: python
python:
  - "3.6"
env:
  - TIMEZONE=Europe/Kiev
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source=. -m unittest discover
after_success:
  - coveralls

