EXAMPLE_RESPONSE_SUCCESS_STATUS = "success"

EXAMPLE_RESPONSE_ERROR_STATUS = "error"
EXAMPLE_RESPONSE_ERROR_MESSAGE = "Error message"

EXAMPLE_RESPONSE_FAILURE_STATUS = "failure"
EXAMPLE_RESPONSE_FAILURE_MESSAGE = "Something went wrong"

EXAMPLE_RESPONSE_ERROR = "Validation error description"
