TRANSACTION_DATA = {
    "AUT_MY_CRF": "123",
    "AUT_MY_MFO": "123",
    "AUT_MY_ACC": "UA123",
    "AUT_MY_NAM": "asd",
    "AUT_MY_MFO_NAME": "asd",
    "AUT_MY_MFO_CITY": "asd",
    "AUT_CNTR_CRF": "123",
    "AUT_CNTR_MFO": "123",
    "AUT_CNTR_ACC": "UA123",
    "AUT_CNTR_NAM": "asd",
    "AUT_CNTR_MFO_NAME": "asd",
    "AUT_CNTR_MFO_CITY": "asd",
    "CCY": "UAH",
    "FL_REAL": "r",
    "PR_PR": "r",
    "DOC_TYP": "p",
    "NUM_DOC": "123",
    "DAT_KL": "03.01.2026",
    "DAT_OD": "03.01.2026",
    "OSND": "asd",
    "SUM": "20000.00",
    "SUM_E": "20000.00",
    "REF": "123",
    "REFN": "1",
    "TIM_P": "22: 49",
    "DATE_TIME_DAT_OD_TIM_P": "01.01.2026 12:00:00",
    "ID": "123",
    "TRANTYPE": "C",
    "DLR": "asd",
    "TECHNICAL_TRANSACTION_ID": "123",
    "UETR": "123",
    "ULTMT": "N",
}
